bbom16
LandvibeDev/VueStudy pull request #11
Opened 2017-09-23 16:25 UTC by bbom16

조건부, 리스트 렌더링

2017-09-24 07:16 UTC, KeonHee requested changes
수정해서 푸쉬 다시해줘~

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/conditional_Rendering.md
> +~~~
`  ```js ` 라고 하면 javascirpt로 ` ```html ` 라고하면 html으로 렌더링해줌

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/conditional_Rendering.md
> +
v-if와 v-show를 사용한 것을 크롬 개발자 도구로 봤을때 어떻게 렌더링되는지 차이점을 보여줬으면 좋겠다

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/list_Rendering.md
> +#List Rendering
#치고 한칸 띄워야함

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/list_Rendering.md
> +~~~
` ```js`

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/list_Rendering.md
> +//html
` ```html `

2017-09-24 07:16 UTC, KeonHee commented on seminar/week3/conditional&list/list_Rendering.md
> +~~~
위와 아래 예제의 결과적인 차이를 보여줘야할듯

위 예제는 for문은 일단 실행되고 ```!todo.isComplete ```에 따라 렌더링 결과가 결정된다
아래 예제는 ```shouldRenderTodos```에 따라 for문이 아예 실행되지 않는다

2017-09-24 13:41 UTC, bbom16 commented on seminar/week3/conditional&list/conditional_Rendering.md
> +
네네 이건 발표하면서 보여줄게요

2017-09-25 04:34 UTC, KeonHee requested changes
수정좀!

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
html

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
html

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
html

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
html

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
js

2017-09-25 04:34 UTC, KeonHee commented on seminar/week3/list_Rendering.md
> +```
js

2017-09-25 05:28 UTC, merged