vue instance
LandvibeDev/VueStudy pull request #5
Opened 2017-09-14 14:39 UTC by silver432

제곧내

2017-09-14 16:12 UTC, KeonHee requested changes
내용도 많이 부실하고 이 주제에 대해서 확실히 이해하고 있지 못한 것으로 보인다

그리고 많이 안써봐서 그런지 마크다운 활용 능력이 떨어지긴하는데 성의도 많이 부족해보인다... 앞선 1주차 문서들 참고해서 다시 작성하도록!

@dhparkhub @yk1028  리뷰 고고

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +```vue
해당 코드가 하이라이팅될 언어를 써야함 ```js

```js
import Vue from 'vue'

Vue.config.productionTip = false

/* eslint-disable no-new */
var myVue = new Vue({
  el: '#app',
  data: {
    a: 1,
    message: '안녕하세요 Vue'
  },
  methods: {
    plus: function () {
      this.a++
    }
  }
})
console.log(myVue.$el)
myVue.plus()
console.log(myVue.$data.a)
``

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +```instance
얘도 js로 바꾸삼

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +ViewModel이 View로 부터 event를 받아들여 Model로 전달하고 DB나 네트워크 처리를 담당하는 Model에서 Data binding을 시켜 View로 전달
MVC 패턴을 모른다면?

MVVM에 대한 설명도 부족

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +![lifecycle](https://kr.vuejs.org/images/lifecycle.png)
사진너무큼

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +```
created > mounted > updated > destroyed 의 라이프사이클을 모두 확인할 수 있는 예제가 있었으면 좋겠음

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +ViewModel이 View로 부터 event를 받아들여 Model로 전달하고 DB나 네트워크 처리를 담당하는 Model에서 Data binding을 시켜 View로 전달
MVVM과 Vue간의 연관성이 하나도 나타나있지않음

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +methods옵션은 Vue객체가 가지고 있는 함수를 나타낸다.<br><br>
코드에 주석으로 넣는게 더 나아보임

```js
import Vue from 'vue'

var myVue = new Vue({
  el: '#app',  // DOM 엘리먼트에  Vue객체를 마운트(연결) 할 때 사용된다.
  data: {      // Vue객체가 가지고 있는 데이터
    a: 1,
    name: 'Vue'
  },
  methods: {   // Vue객체가 가지고 있는 함수
    message: function () {
      return 'Hello' + this.name;
    }
    plus: function () {
       this.a++
    }
  }
})
console.log(myVue.$el)
myVue.plus()
console.log(myVue.$data.a)
```

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>firstprac</title>
</head>
<body>
    <div id="app">  <!-- Vue객체가 마운트될 DOM 엘리먼트 -->
        {{ name }}  <!-- data 렌더링 -->
        {{ message ()  }}  <!-- method 실행, return값 렌더링 -->
    </div>
</body>
</html>
```

2017-09-14 16:12 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +- el,data,methods
나열만 해놓고 설명은 맨아래에 있으니까 보기가 불편함

활용적인 부분은 코드로 충분이 표현가능하니까

이곳에서는 코드에 앞서 개념적인 부분을 추가했으면 좋겠음

>각 Vue 인스턴스는 data 객체에 있는 모든 속성을 프록시 처리 합니다.

>데이터가 변경되면 화면은 다시 렌더링됩니다. data의 속성은 인스턴스가 생성될때 있었다면 반응형입니다. 즉 다음과 같이 새 속성을 추가합니다.

Vue 공홈 내용인데 중요한 내용이라고 생각함. 공부하고 잘 정리 해봤으면 좋겠다

2017-09-17 12:21 UTC, KeonHee requested changes
마지막!

2017-09-17 12:21 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +### MVC 패턴
MVC는 ###이고 MVVM은 ##이네

2017-09-17 12:21 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +- el,data,methods<br>
>각 Vue 인스턴스는 data 객체에 있는 모든 속성을 프록시 처리 합니다.

>데이터가 변경되면 화면은 다시 렌더링됩니다. data의 속성은 인스턴스가 생성될때 있었다면 반응형입니다. 즉 다음과 같이 새 속성을 추가합니다.

이 내용들 중요하니까 추가좀~

2017-09-17 12:21 UTC, KeonHee commented on seminar/week2/vue-instance/md/vue_instance.md
> +    </div>
띄어쓰기

2017-09-17 14:41 UTC, yk1028 approved these changes
$가 뭔지 설명해주면 좋을듯
굿

2017-09-18 10:43 UTC, merged