dhpark upload study docs
LandvibeDev/VueStudy pull request #7
Opened 2017-09-17 10:18 UTC by dhparkhub

dhpark upload study docs

2017-09-17 12:40 UTC, KeonHee requested changes
공홈의 어색한 번역투들이 많이 보임, 예제도 공홈 그대로 쓰지 말고 변형해서 썻으면하는 아쉬움이~

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/03.html
> +  <script src="https://unpkg.com/lodash@4.13.1/lodash.min.js"></script>
lodash에 대한 간단한 설명해주면 좋을듯

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +없는 한 계산된 속성의 함수는 `이전의 계산된 결과를 즉시 반환`하여 불필요한 함수의 호출을 방지할 수 있다.
computed와 methods의 차이점은 **캐싱**에 있다. methods의 함수들은 호출할 때마다 함수를 실행하지만, computed의 함수들은 내부 데이터들의 변환이 없는이상 이전의 결과를 즉시 반환하여 불필요한 함수의 호출을 방지할 수 있다.

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +없는 한 계산된 속성의 함수는 `이전의 계산된 결과를 즉시 반환`하여 불필요한 함수의 호출을 방지할 수 있다.
computed는 예약어이기 때문에 원문 그대로 쓰는 것이 좋음

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +계산된 속성의 함수로 정의하면 하나의 함수에 5가지 변수를 종속적으로 설계할 수 있다.
감시자 함수 -> watcher 함수, 계산된  -> computed

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +```
lodash의 _. debounce, _.capitalize 같이 주제와는 상관없는 라이브러리 함수와 한번에 이해하기 힘들만한 로직들에 대한 부연 설명이 필요할듯

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +계산된 속성은 기본저그로는 `getter` 함수만 가지고 있지만 필요에 따라 `setter` 함수를 선언할 수 있는데
기본적으로는

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/README.md
> +`getter`, `setter` 함수에 대한 이해가 있으면 따로 설명할 소프트웨어 디자인의 이슈는 없다.
Java의 getter, setter와 유사한 개념이다

2017-09-17 12:40 UTC, KeonHee commented on seminar/week2/04/01.html
> +  <script src="https://unpkg.com/vue"></script>
굿

2017-09-17 14:34 UTC, yk1028 approved these changes
computed랑 watch에 대한 기본적인 정의나 설명같은게 들어가면 좋을 것 같아요. 수고하셧습니다.

2017-09-17 16:53 UTC, silver432 commented on seminar/week2/04/README.md
> +```
저도 감시자 부분코드에 대한 설명이 필요한거 같네요

2017-09-18 10:14 UTC, KeonHee reviewed
dddd

2017-09-18 10:14 UTC, KeonHee commented on seminar/week2/04/01.html
> +  <title>Vue.js Study</title>
sdfdfd

2017-09-18 10:14 UTC, KeonHee commented on seminar/week2/04/01.html
> +    <p>reversed: {{ message.split('').reverse().join('') }}</p>
dfdfd

2017-09-18 10:29 UTC, merged